version: '3.8'

services:
  edgeone-origin-hacked:
    build: mayflydestiny/edgeone-dogroup:latest
    container_name: edgeone-dogroup
    volumes:
      - ./config:/eodo
    network_mode: host
    restart: unless-stopped