DingTalkWebhook: ''
DnsPodRecord: []
EdgeOneZoneId: []
IPv6SelectMode: auto
IPv6ValidityCheck: true
IntervalMin: 15
SelectIface: ''
SelectedIPv6Addresses: []
TencentCloud:
  SecretId: ''
  SecretKey: ''
